server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://db.yaoewmsebqbvdhrcorfq.supabase.co:5432/postgres
    username: postgres
    password: KKimsuhyun1!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: classpath:/static/, file:./src/main/resources/static/

file:
  upload-dir: uploads